def my_function():
    x = 10  # Local variable
    print("Inside function:", x)
 
my_function()
#print(x)  # This will cause an error because x is local to my_function
 